name: CD - Deploy

on:
  workflow_run:
    workflows: ["Docker - Build & Push"]
    types:
      - completed

jobs:
  deploy-dev:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy DEV
        run: echo "Deploy dev automÃ¡tico aqui"

  deploy-prod:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment: production  # ðŸ”¥ AQUI estÃ¡ o gate

    steps:
      - name: Deploy PROD
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/loja-app:latest
            sudo docker stop loja || true
            sudo docker rm loja || true
            sudo docker run -d -p 80:8080 --name loja ${{ secrets.DOCKERHUB_USERNAME }}/loja-app:latest


          